// =================== ОТДЕЛЬНЫЙ КАТАЛОГ УПРАЖНЕНИЙ ===================
// Этот файл содержит все упражнения для страницы "Список упражнений"
// Он не зависит от тренировок и используется только для каталога
 
const EXERCISES_CATALOG = [
    // ====================================================================
    // СИЛОВЫЕ
    // ====================================================================

    // ===== ГРУДЬ =====
    { name: 'Жим штанги лёжа', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Жим штанги на наклонной скамье', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Жим гантелей лёжа', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Жим гантелей на наклонной скамье', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Разводка гантелей лёжа', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Разводка гантелей на наклонной скамье', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Сведение рук в кроссовере', category: 'Грудь', sets: 4, reps: 15, icon: 'breast' },
    { name: 'Отжимания от пола', category: 'Грудь', sets: 4, reps: 20, icon: 'breast' },
    { name: 'Отжимания широким хватом', category: 'Грудь', sets: 4, reps: 15, icon: 'breast' },
    { name: 'Отжимания на брусьях', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Отжимания с хлопком', category: 'Грудь', sets: 4, reps: 10, icon: 'breast' },
    { name: 'Отжимания с ногами на возвышении', category: 'Грудь', sets: 4, reps: 15, icon: 'breast' },
    { name: 'Пуловер с гантелью', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Пуловер со штангой', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Жим одной гантели лёжа', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Отжимания с коленей', category: 'Грудь', sets: 4, reps: 15, icon: 'breast' },
    { name: 'Отжимания от стены', category: 'Грудь', sets: 4, reps: 20, icon: 'breast' },
    { name: 'Отжимания с узкой постановкой рук', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Отжимания с паузой внизу', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },
    { name: 'Отжимания в алмаз', category: 'Грудь', sets: 4, reps: 10, icon: 'breast' },
    { name: 'Отжимания на одной руке', category: 'Грудь', sets: 4, reps: 6, icon: 'breast' },
    { name: 'Жим Свенда', category: 'Грудь', sets: 4, reps: 12, icon: 'breast' },

    // ===== СПИНА =====
    { name: 'Подтягивания', category: 'Спина', sets: 4, reps: 10, icon: 'back' },
    { name: 'Подтягивания широким хватом', category: 'Спина', sets: 4, reps: 10, icon: 'back' },
    { name: 'Подтягивания узким хватом', category: 'Спина', sets: 4, reps: 10, icon: 'back' },
    { name: 'Подтягивания обратным хватом', category: 'Спина', sets: 4, reps: 10, icon: 'back' },
    { name: 'Подтягивания нейтральным хватом', category: 'Спина', sets: 4, reps: 10, icon: 'back' },
    { name: 'Подтягивания с отягощением', category: 'Спина', sets: 4, reps: 8, icon: 'back' },
    { name: 'Тяга штанги к поясу в наклоне', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга штанги к поясу обратным хватом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга гантели к поясу', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга гантели к поясу с упором', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга двух гантелей к поясу', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга вертикального блока широким хватом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга вертикального блока узким хватом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга вертикального блока обратным хватом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга горизонтального блока', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга горизонтального блока широким хватом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Гиперэкстензия', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Гиперэкстензия с весом', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Шраги с гантелями', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Шраги со штангой', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Шраги на тренажёре', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Тяга Т-грифа', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга нижнего блока к груди', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Лодочка', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Лодочка с задержкой', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Супермен', category: 'Спина', sets: 4, reps: 12, icon: 'back' },
    { name: 'Тяга резинки к груди', category: 'Спина', sets: 4, reps: 15, icon: 'back' },
    { name: 'Тяга резинки к поясу', category: 'Спина', sets: 4, reps: 15, icon: 'back' },

    // ===== НОГИ =====
    { name: 'Приседания со штангой', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Приседания с гантелями', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Приседания плие', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Приседания плие с гантелью', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Фронтальные приседания', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Приседания с паузой внизу', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Приседания с выпрыгиванием', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Приседания у стены', category: 'Ноги', sets: 4, reps: '45 сек', icon: 'legs' },
    { name: 'Приседания с задержкой', category: 'Ноги', sets: 4, reps: '30 сек', icon: 'legs' },
    { name: 'Выпады с гантелями', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады с гантелями на правую ногу', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады с гантелями на левую ногу', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады со штангой', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады с прыжком', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады назад с гантелями', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Выпады в стороны', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Болгарские сплит-приседания', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Болгарские сплит-приседания на правую ногу', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Болгарские сплит-приседания на левую ногу', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Румынская тяга с гантелями', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Румынская тяга со штангой', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Мёртвая тяга', category: 'Ноги', sets: 4, reps: 10, icon: 'legs' },
    { name: 'Мёртвая тяга с гантелями', category: 'Ноги', sets: 4, reps: 12, icon: 'legs' },
    { name: 'Становая тяга', category: 'Ноги', sets: 4, reps: 10, icon: 'legs' },
    { name: 'Сгибание ног лёжа', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Разгибание ног сидя', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Подъём на носки стоя', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Подъём на носки с гантелями', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Подъём на носки в тренажёре', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Подъём на носки сидя', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Ягодичный мостик', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Ягодичный мостик с гантелью', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Ягодичный мостик со штангой', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Ягодичный мостик на одной ноге', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Ягодичный мостик на правую ногу', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Ягодичный мостик на левую ногу', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },
    { name: 'Отведение ноги в сторону с резинкой', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Отведение ноги в сторону на правую ногу', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Отведение ноги в сторону на левую ногу', category: 'Ноги', sets: 4, reps: 20, icon: 'legs' },
    { name: 'Махи ногой назад', category: 'Ноги', sets: 4, reps: 15, icon: 'legs' },

    // ===== ПЛЕЧИ =====
    { name: 'Жим гантелей сидя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Жим гантелей стоя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Жим штанги стоя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Жим штанги сидя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Жим Арнольда', category: 'Плечи', sets: 4, reps: 10, icon: 'shoulder' },
    { name: 'Жим Арнольда сидя', category: 'Плечи', sets: 4, reps: 10, icon: 'shoulder' },
    { name: 'Жим в машине Смита', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Разводка гантелей в стороны стоя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Разводка гантелей в стороны сидя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Разводка гантелей в наклоне', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Разводка гантелей в наклоне сидя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Тяга к подбородку', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Тяга к подбородку широким хватом', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Тяга к подбородку с резинкой', category: 'Плечи', sets: 4, reps: 15, icon: 'shoulder' },
    { name: 'Подъём рук перед собой с гантелями', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Подъём рук перед собой со штангой', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Подъём рук перед собой с резинкой', category: 'Плечи', sets: 4, reps: 15, icon: 'shoulder' },
    { name: 'Отжимания в стойке у стены', category: 'Плечи', sets: 4, reps: 8, icon: 'shoulder' },
    { name: 'Отжимания в стойке с опорой', category: 'Плечи', sets: 4, reps: 8, icon: 'shoulder' },
    { name: 'Махи гантелями перед собой', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Разведение рук с резинкой в стороны', category: 'Плечи', sets: 4, reps: 15, icon: 'shoulder' },
    { name: 'Жим одной гантели сидя', category: 'Плечи', sets: 4, reps: 12, icon: 'shoulder' },
    { name: 'Подъём рук в стороны с резинкой', category: 'Плечи', sets: 4, reps: 15, icon: 'shoulder' },

    // ===== ПРЕСС =====
    { name: 'Скручивания лёжа', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Скручивания с вытянутыми руками', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Скручивания с весом', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Скручивания на наклонной скамье', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Обратные скручивания', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },
    { name: 'Подъём ног в висе', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },
    { name: 'Подъём ног в висе с весом', category: 'Пресс', sets: 4, reps: 12, icon: 'press' },
    { name: 'Подъём ног лёжа', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },
    { name: 'Ножницы ногами', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Велосипед лёжа', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Планка на локтях', category: 'Пресс', sets: 4, reps: '30 сек', icon: 'press' },
    { name: 'Планка на вытянутых руках', category: 'Пресс', sets: 4, reps: '30 сек', icon: 'press' },
    { name: 'Планка с подъёмом ног', category: 'Пресс', sets: 4, reps: '30 сек', icon: 'press' },
    { name: 'Планка с касанием плеч', category: 'Пресс', sets: 4, reps: 16, icon: 'press' },
    { name: 'Планка на коленях', category: 'Пресс', sets: 4, reps: '20 сек', icon: 'press' },
    { name: 'Боковая планка', category: 'Пресс', sets: 4, reps: '25 сек', icon: 'press' },
    { name: 'Боковая планка на правую сторону', category: 'Пресс', sets: 4, reps: '25 сек', icon: 'press' },
    { name: 'Боковая планка на левую сторону', category: 'Пресс', sets: 4, reps: '25 сек', icon: 'press' },
    { name: 'Боковая планка с подъёмом ноги', category: 'Пресс', sets: 4, reps: '25 сек', icon: 'press' },
    { name: 'Твист сидя', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Твист сидя с весом', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Твист корпуса с гантелью', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },
    { name: 'Вакуум живота стоя', category: 'Пресс', sets: 4, reps: '10 сек', icon: 'press' },
    { name: 'Вакуум живота лёжа', category: 'Пресс', sets: 4, reps: '10 сек', icon: 'press' },
    { name: 'Вакуум живота сидя', category: 'Пресс', sets: 4, reps: '10 сек', icon: 'press' },
    { name: 'Книжка (складывание)', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },
    { name: 'Русский твист', category: 'Пресс', sets: 4, reps: 20, icon: 'press' },
    { name: 'Подъём таза лёжа', category: 'Пресс', sets: 4, reps: 15, icon: 'press' },

    // ===== РУКИ =====
    { name: 'Сгибание рук с гантелями', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с гантелями стоя', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с гантелями сидя', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с гантелями на скамье Скотта', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук со штангой', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук со штангой широким хватом', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук со штангой узким хватом', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с EZ-штангой', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Молотковые сгибания', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с резинкой', category: 'Руки', sets: 4, reps: 15, icon: 'bodybuilding' },
    { name: 'Сгибание рук в кроссовере', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Французский жим с гантелью стоя', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Французский жим с гантелью сидя', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Французский жим со штангой лёжа', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Французский жим с EZ-штангой лёжа', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Жим лёжа узким хватом', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Отжимания узким хватом', category: 'Руки', sets: 4, reps: 15, icon: 'bodybuilding' },
    { name: 'Алмазные отжимания', category: 'Руки', sets: 4, reps: 10, icon: 'bodybuilding' },
    { name: 'Обратные отжимания от стула', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Обратные отжимания от стула с весом', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Разгибание рук с резинкой', category: 'Руки', sets: 4, reps: 15, icon: 'bodybuilding' },
    { name: 'Разгибание рук в кроссовере', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с гантелями хватом молот', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Сгибание рук с гантелями на нижнем блоке', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Разгибание рук с гантелью из-за головы', category: 'Руки', sets: 4, reps: 12, icon: 'bodybuilding' },
    { name: 'Отжимания на одной руке на правую руку', category: 'Руки', sets: 4, reps: 6, icon: 'bodybuilding' },
    { name: 'Отжимания на одной руке на левую руку', category: 'Руки', sets: 4, reps: 6, icon: 'bodybuilding' },

    // ===== ВСЁ ТЕЛО =====
    { name: 'Бёрпи', category: 'Всё тело', sets: 4, reps: 15, icon: 'WholeBody' },
    { name: 'Бёрпи с прыжком вверх', category: 'Всё тело', sets: 4, reps: 12, icon: 'WholeBody' },
    { name: 'Бёрпи упрощённые', category: 'Всё тело', sets: 4, reps: 15, icon: 'WholeBody' },
    { name: 'Скакалка', category: 'Всё тело', sets: 4, reps: '30 сек', icon: 'WholeBody' },
    { name: 'Прыжки из приседа', category: 'Всё тело', sets: 4, reps: 15, icon: 'WholeBody' },
    { name: 'Бег с высоким подниманием колен', category: 'Всё тело', sets: 4, reps: '20 сек', icon: 'WholeBody' },
    { name: 'Джампинг Джек', category: 'Всё тело', sets: 4, reps: 20, icon: 'WholeBody' },
    { name: 'Джампинг Джек с утяжелением', category: 'Всё тело', sets: 4, reps: 20, icon: 'WholeBody' },
    { name: 'Горные лыжи', category: 'Всё тело', sets: 4, reps: 20, icon: 'WholeBody' },
    { name: 'Горные лыжи с отягощением', category: 'Всё тело', sets: 4, reps: 20, icon: 'WholeBody' },

    // ====================================================================
    // ФИТНЕС
    // ====================================================================

    // ===== КАРДИО =====
    { name: 'Бег на месте', category: 'Кардио', sets: 3, reps: '30 сек', icon: 'cardio' },
    { name: 'Бег на месте с высокими коленями', category: 'Кардио', sets: 3, reps: '30 сек', icon: 'cardio' },
    { name: 'Бег на месте с захлёстом голеней', category: 'Кардио', sets: 3, reps: '30 сек', icon: 'cardio' },
    { name: 'Прыжки на месте', category: 'Кардио', sets: 3, reps: 20, icon: 'cardio' },
    { name: 'Горные лыжи', category: 'Кардио', sets: 3, reps: 20, icon: 'cardio' },
    { name: 'Прыжки со сменой ног', category: 'Кардио', sets: 3, reps: 20, icon: 'cardio' },
    { name: 'Прыжки ноги вместе-врозь', category: 'Кардио', sets: 3, reps: 20, icon: 'cardio' },
    { name: 'Бёрпи упрощённые', category: 'Кардио', sets: 3, reps: 10, icon: 'cardio' },
    { name: 'Прыжки из приседа', category: 'Кардио', sets: 3, reps: 15, icon: 'cardio' },
    { name: 'Ходьба с высоким подниманием колен', category: 'Кардио', sets: 3, reps: '20 сек', icon: 'cardio' },
    { name: 'Ходьба с захлёстом голеней', category: 'Кардио', sets: 3, reps: '20 сек', icon: 'cardio' },
    { name: 'Степ-ап (шаги на платформу)', category: 'Кардио', sets: 3, reps: 15, icon: 'cardio' },
    { name: 'Звезда (прыжки с разведением рук и ног)', category: 'Кардио', sets: 3, reps: 15, icon: 'cardio' },

    // ===== РАСТЯЖКА =====
    { name: 'Наклоны к ногам сидя', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Наклоны к ногам стоя', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Глубокий наклон к ногам', category: 'Растяжка', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Растяжка шеи', category: 'Растяжка', sets: 3, reps: '15 сек', icon: 'stretching' },
    { name: 'Растяжка шеи с руками', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Растяжка шеи с сопротивлением', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Растяжка рук за спиной', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Растяжка трицепса', category: 'Растяжка', sets: 3, reps: '15 сек', icon: 'stretching' },
    { name: 'Растяжка плеч (замок)', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Растяжка плеч за спиной', category: 'Растяжка', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Наклоны в стороны', category: 'Растяжка', sets: 3, reps: '15 сек', icon: 'stretching' },
    { name: 'Боковые наклоны с руками', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Боковые наклоны с захватом', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Растяжка спины (кошка-корова)', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Растяжка спины (скручивание)', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Растяжка спины на полу (скручивание)', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Растяжка позвоночника (мост)', category: 'Растяжка', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Растяжка ног (шпагат)', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Продольный шпагат', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Поперечный шпагат', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Поза голубя', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Поза верблюда', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Поза ребёнка', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Складка с захватом стоп', category: 'Растяжка', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Растяжка задней поверхности бедра', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Бабочка', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Ягодичный мостик (статический)', category: 'Растяжка', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Поза лука', category: 'Растяжка', sets: 3, reps: '25 сек', icon: 'stretching' },

    // ===== РАСТЯЖКА ПОЗВОНОЧНИКА =====
    { name: 'Вис на турнике', category: 'Растяжка позвоночника', sets: 3, reps: '15 сек', icon: 'stretching' },
    { name: 'Вис на турнике с отягощением', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Наклоны вперёд сидя', category: 'Растяжка позвоночника', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Глубокий наклон вперёд с захватом ног', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Глубокий наклон с захватом стоп', category: 'Растяжка позвоночника', sets: 3, reps: '35 сек', icon: 'stretching' },
    { name: 'Кошка-корова', category: 'Растяжка позвоночника', sets: 3, reps: 10, icon: 'stretching' },
    { name: 'Кошка-корова с задержкой', category: 'Растяжка позвоночника', sets: 3, reps: 15, icon: 'stretching' },
    { name: 'Скручивание лёжа (позвоночник)', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Скручивание позвоночника сидя', category: 'Растяжка позвоночника', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Поза верблюда', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Поза лука', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Мост (позвоночник)', category: 'Растяжка позвоночника', sets: 3, reps: '30 сек', icon: 'stretching' },
    { name: 'Стойка на лопатках', category: 'Растяжка позвоночника', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Наклоны в стороны стоя', category: 'Растяжка позвоночника', sets: 3, reps: '15 сек', icon: 'stretching' },
    { name: 'Наклоны в стороны с весом', category: 'Растяжка позвоночника', sets: 3, reps: '20 сек', icon: 'stretching' },
    { name: 'Растяжка спины на фитболе', category: 'Растяжка позвоночника', sets: 3, reps: '25 сек', icon: 'stretching' },
    { name: 'Растяжка спины с резинкой', category: 'Растяжка позвоночника', sets: 3, reps: '30 сек', icon: 'stretching' },

    // ===== ЗАРЯДКА =====
    { name: 'Наклоны головы', category: 'Зарядка', sets: 3, reps: 10, icon: 'charging' },
    { name: 'Наклоны головы с сопротивлением', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Вращение плечами', category: 'Зарядка', sets: 3, reps: 10, icon: 'charging' },
    { name: 'Вращение плечами с гантелями', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Наклоны туловища', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Наклоны туловища с весом', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Приседания', category: 'Зарядка', sets: 3, reps: 15, icon: 'charging' },
    { name: 'Приседания с гантелями', category: 'Зарядка', sets: 3, reps: 15, icon: 'charging' },
    { name: 'Махи ногами', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Махи ногами с утяжелением', category: 'Зарядка', sets: 3, reps: 15, icon: 'charging' },
    { name: 'Круговые движения тазом', category: 'Зарядка', sets: 3, reps: 10, icon: 'charging' },
    { name: 'Потягивание вверх', category: 'Зарядка', sets: 3, reps: 10, icon: 'charging' },
    { name: 'Планка', category: 'Зарядка', sets: 3, reps: '20 сек', icon: 'charging' },
    { name: 'Планка с подъемом рук', category: 'Зарядка', sets: 3, reps: '30 сек', icon: 'charging' },
    { name: 'Выпады на месте', category: 'Зарядка', sets: 3, reps: 10, icon: 'charging' },
    { name: 'Выпады с прыжком', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Вращение корпусом с гантелью', category: 'Зарядка', sets: 3, reps: 12, icon: 'charging' },
    { name: 'Твист корпуса с гантелью', category: 'Зарядка', sets: 3, reps: 15, icon: 'charging' },

    // ===== ПИЛАТЕС =====
    { name: 'Сотня (дыхание + руки)', category: 'Пилатес', sets: 3, reps: 10, icon: 'Pilates' },
    { name: 'Сотня с вытянутыми ногами', category: 'Пилатес', sets: 3, reps: 15, icon: 'Pilates' },
    { name: 'Сотня с отягощением', category: 'Пилатес', sets: 3, reps: 20, icon: 'Pilates' },
    { name: 'Скручивание с подъемом ног', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Скручивание с подъемом ног и рук', category: 'Пилатес', sets: 3, reps: 20, icon: 'Pilates' },
    { name: 'Подъем таза лёжа', category: 'Пилатес', sets: 3, reps: 15, icon: 'Pilates' },
    { name: 'Подъем таза на правую ногу', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Подъем таза на левую ногу', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Подъем таза с гантелью', category: 'Пилатес', sets: 3, reps: 15, icon: 'Pilates' },
    { name: 'Ножницы ногами', category: 'Пилатес', sets: 3, reps: 15, icon: 'Pilates' },
    { name: 'Ножницы ногами с утяжелением', category: 'Пилатес', sets: 3, reps: 20, icon: 'Pilates' },
    { name: 'Мостик с подъемом ноги', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Мостик с подъемом ноги на правую ногу', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Мостик с подъемом ноги на левую ногу', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Планка на коленях', category: 'Пилатес', sets: 3, reps: '20 сек', icon: 'Pilates' },
    { name: 'Планка на локтях', category: 'Пилатес', sets: 3, reps: '30 сек', icon: 'Pilates' },
    { name: 'Планка с подъемом ноги', category: 'Пилатес', sets: 3, reps: '35 сек', icon: 'Pilates' },
    { name: 'Планка с подъемом ноги на правую ногу', category: 'Пилатес', sets: 3, reps: '40 сек', icon: 'Pilates' },
    { name: 'Планка с подъемом ноги на левую ногу', category: 'Пилатес', sets: 3, reps: '40 сек', icon: 'Pilates' },
    { name: 'Боковая планка', category: 'Пилатес', sets: 3, reps: '20 сек', icon: 'Pilates' },
    { name: 'Боковая планка с подъемом ноги', category: 'Пилатес', sets: 3, reps: '25 сек', icon: 'Pilates' },
    { name: 'Боковая планка с подъемом ноги на правую сторону', category: 'Пилатес', sets: 3, reps: '25 сек', icon: 'Pilates' },
    { name: 'Боковая планка с подъемом ноги на левую сторону', category: 'Пилатес', sets: 3, reps: '25 сек', icon: 'Pilates' },
    { name: 'Лодочка', category: 'Пилатес', sets: 3, reps: 12, icon: 'Pilates' },
    { name: 'Лодочка с задержкой', category: 'Пилатес', sets: 3, reps: 15, icon: 'Pilates' },
    { name: 'Боковые наклоны сидя', category: 'Пилатес', sets: 3, reps: 10, icon: 'Pilates' },
    { name: 'Растяжка позвоночника (кошка)', category: 'Пилатес', sets: 3, reps: 10, icon: 'Pilates' },
    { name: 'Растяжка в позе голубя', category: 'Пилатес', sets: 3, reps: '20 сек', icon: 'Pilates' },
    { name: 'Стойка на лопатках', category: 'Пилатес', sets: 3, reps: '20 сек', icon: 'Pilates' },

    // ====================================================================
    // PREMIUM
    // ====================================================================

    // ===== КРОССФИТ =====
    { name: 'Бёрпи с отжиманием', category: 'Кроссфит', sets: 4, reps: 15, icon: 'crossfit' },
    { name: 'Бёрпи с прыжком на тумбу', category: 'Кроссфит', sets: 4, reps: 10, icon: 'crossfit' },
    { name: 'Джампинг Джек с утяжелением', category: 'Кроссфит', sets: 4, reps: 25, icon: 'crossfit' },
    { name: 'Приседания со штангой', category: 'Кроссфит', sets: 4, reps: 15, icon: 'crossfit' },
    { name: 'Прыжки из приседа', category: 'Кроссфит', sets: 4, reps: 20, icon: 'crossfit' },
    { name: 'Горные лыжи с отягощением', category: 'Кроссфит', sets: 4, reps: 20, icon: 'crossfit' },
    { name: 'Бёрпи с прыжком вверх', category: 'Кроссфит', sets: 4, reps: 12, icon: 'crossfit' },
    { name: 'Отжимания с хлопком', category: 'Кроссфит', sets: 4, reps: 12, icon: 'crossfit' },
    { name: 'Приседания с выпрыгиванием', category: 'Кроссфит', sets: 4, reps: 15, icon: 'crossfit' },
    { name: 'Планка с отягощением', category: 'Кроссфит', sets: 4, reps: '40 сек', icon: 'crossfit' },

    // ===== МУЖСКАЯ СИЛА =====
    { name: 'Кегель для мужчин', category: 'Мужская сила', sets: 4, reps: 20, icon: 'men' },
    { name: 'Ягодичный мостик с гантелью', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Ягодичный мостик на правую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Ягодичный мостик на левую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Боковая планка с подъемом ноги', category: 'Мужская сила', sets: 4, reps: '25 сек', icon: 'men' },
    { name: 'Болгарские сплит-приседания', category: 'Мужская сила', sets: 4, reps: 12, icon: 'men' },
    { name: 'Румынская тяга с гантелями', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Отведение ноги в сторону с резинкой на правую ногу', category: 'Мужская сила', sets: 4, reps: 20, icon: 'men' },
    { name: 'Отведение ноги в сторону с резинкой на левую ногу', category: 'Мужская сила', sets: 4, reps: 20, icon: 'men' },
    { name: 'Выпады с прыжком на правую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Выпады с прыжком на левую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Боковые выпады с гантелью на правую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Боковые выпады с гантелью на левую ногу', category: 'Мужская сила', sets: 4, reps: 15, icon: 'men' },
    { name: 'Планка с отягощением на тазу', category: 'Мужская сила', sets: 4, reps: '35 сек', icon: 'men' },
    { name: 'Махи ногой назад с резинкой на правую ногу', category: 'Мужская сила', sets: 4, reps: 20, icon: 'men' },
    { name: 'Махи ногой назад с резинкой на левую ногу', category: 'Мужская сила', sets: 4, reps: 20, icon: 'men' },

    // ===== ЖЕНСКОЕ СЧАСТЬЕ =====
    { name: 'Кегель для женщин', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Ягодичный мостик с гантелью', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Ягодичный мостик на правую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Ягодичный мостик на левую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Приседания плие с гантелью', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Боковая планка на правую сторону', category: 'Женское счастье', sets: 4, reps: '30 сек', icon: 'woman' },
    { name: 'Боковая планка на левую сторону', category: 'Женское счастье', sets: 4, reps: '30 сек', icon: 'woman' },
    { name: 'Планка с подъемом ноги на правую ногу', category: 'Женское счастье', sets: 4, reps: '40 сек', icon: 'woman' },
    { name: 'Планка с подъемом ноги на левую ногу', category: 'Женское счастье', sets: 4, reps: '40 сек', icon: 'woman' },
    { name: 'Махи ногой назад с утяжелением на правую ногу', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Махи ногой назад с утяжелением на левую ногу', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Отведение ноги в сторону с резинкой на правую ногу', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Отведение ноги в сторону с резинкой на левую ногу', category: 'Женское счастье', sets: 4, reps: 20, icon: 'woman' },
    { name: 'Болгарские сплит-приседания на правую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Болгарские сплит-приседания на левую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Выпады с прыжком на правую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Выпады с прыжком на левую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Румынская тяга с гантелями', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Боковые выпады с гантелью на правую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Боковые выпады с гантелью на левую ногу', category: 'Женское счастье', sets: 4, reps: 15, icon: 'woman' },
    { name: 'Махи ногой назад с резинкой на правую ногу', category: 'Женское счастье', sets: 4, reps: 25, icon: 'woman' },
    { name: 'Махи ногой назад с резинкой на левую ногу', category: 'Женское счастье', sets: 4, reps: 25, icon: 'woman' },
];